# Generated by Django 2.2.4 on 2019-08-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190515_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thieflocation',
            name='national_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
