# Generated by Django 2.2.4 on 2019-09-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190824_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thieflocation',
            options={'ordering': ['-id']},
        ),
    ]
